#!/bin/bash

env GO111MODULE=off go get -u github.com/alecthomas/gometalinter
go build -v -gcflags '-m -l' -ldflags '-s -w' -o /dev/null || true
gometalinter --vendor --disable-all --enable=vetshadow \
  --enable=golint --enable=ineffassign --enable=goconst --enable=gocyclo \
      --enable=deadcode --tests ./...
